### ISSUE TITLE
link to pdf problem with java 17: GridLayoutBag protected instead of public

### ISSUE THREAD

**Issue by Illegit** [lilive/Freeplane-Scripts#1]
Hi lilive,  many of your scripts are very valuable, I'm even using the link to pdf groovy, but I got an issue moving from java8 to java17, please, if you are available,  refer to the issue #301 in the Freeplane issues Github.
Hope you can help solve this issue.
In any case, I appreciated a lot your tools.
Best regards
illegit

**Comment by lilive** [comment]
Hi Illegit,
Perhaps you are still interested on this topic :wink: 
I do not have this issue with my system, but you can try the new version I just made.

**Comment by Illegit** [comment]
Thank you, I have downloaded it, and now to test it I need some days.
illegit
